name: Build
on:
  push:
    branches:
      - "master"
    tags-ignore:
      - "**" # prevent double build on release tag
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - "**"

# Global variables that will be load into every shell
env:
  TEST_REPORT_ESLINT_FOLDER: reports/eslint
  TEST_REPORT_ESLINT_FILENAME: eslint.json

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        run: |
          yarn build
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ runner.os }} # artifacts zip name
          path: |
            dist
